In [1]:
import numpy as np

In [2]:
tracks = np.arange(100)
np.random.seed(0)
# np.random.shuffle(tracks)
shuffled_indices = np.random.permutation(len(tracks))


In [3]:
truth_vtx = np.split(tracks, [18, 41, 77, 86, 92])

In [9]:
reco_vtx = np.split(tracks[shuffled_indices], [18, 41, 77, 86, 92])

In [10]:
match_matrix = np.zeros((len(reco_vtx),len(truth_vtx)))

In [11]:
match_matrix

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
for i in range(len(reco_vtx)):
    for j in range(len(truth_vtx)):
        match_matrix[i,j] = len(np.intersect1d(reco_vtx[i], truth_vtx[j]))

In [13]:
match_matrix

array([[ 4.,  4.,  5.,  1.,  1.,  3.],
       [ 4.,  3., 12.,  2.,  1.,  1.],
       [ 8., 11., 10.,  3.,  2.,  2.],
       [ 0.,  3.,  3.,  2.,  0.,  1.],
       [ 1.,  1.,  2.,  0.,  2.,  0.],
       [ 1.,  1.,  4.,  1.,  0.,  1.]])

In [15]:
# the truth represetative of reco vtx
truth_rep = match_matrix.argmax(axis = 1)


array([2, 2, 1, 1, 2, 2])